/// A discovered feature that maps to a go_router route.
class FeatureRoute {
  /// Route/constant name in camelCase, e.g. `product`, `userProfile`.
  final String routeName;

  /// The view widget class, e.g. `ProductView`.
  final String className;

  /// Package import for the view, e.g.
  /// `package:app/presentation/product/views/product_view.dart`.
  final String importPath;

  const FeatureRoute({
    required this.routeName,
    required this.className,
    required this.importPath,
  });

  /// `home` is rendered as the root path and not duplicated as a constant.
  bool get isHome => routeName == 'home';
}

/// Builds the contents of `app_routes.dart` from the discovered [routes].
/// `home` is always present as `/`; every other route is `'/<name>'`.
String buildAppRoutesFile(List<FeatureRoute> routes) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by `river_cli generate routes`. Re-run to refresh.')
    ..writeln('class AppRoutes {')
    ..writeln('  AppRoutes._();')
    ..writeln()
    ..writeln("  static const String home = '/';");

  for (final r in routes) {
    if (r.isHome) continue;
    buffer.writeln("  static const String ${r.routeName} = '/${r.routeName}';");
  }

  buffer.writeln('}');
  return buffer.toString();
}

/// Builds the contents of `route_page.dart` from the discovered [routes].
/// A feature literally named `home` becomes the `/` route; otherwise `/` shows
/// a [Placeholder].
String buildRoutePageFile(List<FeatureRoute> routes, String pkg) {
  final homeMatches = routes.where((r) => r.isHome);
  final FeatureRoute? home = homeMatches.isEmpty ? null : homeMatches.first;

  final imports = <String>[
    "import 'package:flutter/material.dart';",
    "import 'package:go_router/go_router.dart';",
    "import 'app_routes.dart';",
  ];
  for (final r in routes) {
    imports.add("import '${r.importPath}';");
  }

  final homeBuilder =
      home == null ? 'const Placeholder()' : 'const ${home.className}()';

  final entries = StringBuffer()
    ..writeln('    GoRoute(')
    ..writeln('      name: AppRoutes.home,')
    ..writeln('      path: AppRoutes.home,')
    ..writeln('      builder: (context, state) => $homeBuilder,')
    ..writeln('    ),');

  for (final r in routes) {
    if (r.isHome) continue;
    entries
      ..writeln('    GoRoute(')
      ..writeln('      name: AppRoutes.${r.routeName},')
      ..writeln('      path: AppRoutes.${r.routeName},')
      ..writeln('      builder: (context, state) => const ${r.className}(),')
      ..writeln('    ),');
  }

  return '''
// GENERATED by `river_cli generate routes`. Re-run to refresh.
${imports.join('\n')}

final GoRouter router = GoRouter(
  initialLocation: AppRoutes.home,
  routes: [
${entries.toString().trimRight()}
  ],
);
''';
}

/// Removes the `static const String <routeName> = ...;` line from an
/// `app_routes.dart` body. `home` is preserved.
String removeRouteConstant(String content, String routeName) {
  final pattern = RegExp(
    r'[ \t]*static const String ' +
        RegExp.escape(routeName) +
        r"\s*=\s*'[^']*';\n?",
  );
  return content.replaceAll(pattern, '');
}

/// Removes a feature's `GoRoute(...)` block and its view import from a
/// `route_page.dart` body. [snake] is the snake_case feature name used to match
/// the `<snake>_view.dart` import line.
String removeRouteEntry(String content, String routeName, String snake) {
  var result = content;

  // Remove the GoRoute block (matches our generated shape).
  final route = RegExp(
    r'\n?[ \t]*GoRoute\(\s*name: AppRoutes\.' +
        RegExp.escape(routeName) +
        r',\s*path: AppRoutes\.' +
        RegExp.escape(routeName) +
        r',\s*builder:[^\n]*\n[ \t]*\),',
  );
  result = result.replaceAll(route, '');

  // Remove the matching view import line.
  final import = RegExp(
    r"\n?import '[^']*" + RegExp.escape('${snake}_view.dart') + r"';",
  );
  result = result.replaceAll(import, '');

  return result;
}
