import '../../utils/field_spec.dart';
import '../../utils/json_inference.dart';
import '../../utils/naming.dart';
import '../../utils/project.dart';

/// Code templates shared by the generators. Names are derived from a single
/// input via [Naming]; output adapts to the modules installed in [ProjectContext]
/// (e.g. the widget library and design tokens are used only when present).

/// An immutable data class with `fromJson` / `toJson` / `copyWith` / `toString`,
/// generated from a `--fields` spec.
String modelTemplate(String name, List<FieldSpec> fields) {
  final className = Naming.pascal(name);
  final effective =
      fields.isEmpty ? const [FieldSpec('id', 'String', false)] : fields;

  final declarations = effective.map((f) => '  ${f.declaration}').join('\n');
  final ctorParams = effective.map((f) => '    ${f.ctorParam},').join('\n');
  final fromJson = effective
      .map((f) => '        ${f.name}: ${f.fromJsonExpr()},')
      .join('\n');
  final toJson = effective.map((f) => '        ${f.toJsonEntry()}').join('\n');
  final copyParams =
      effective.map((f) => '    ${f.type}? ${f.name},').join('\n');
  final copyAssign = effective
      .map((f) => '      ${f.name}: ${f.name} ?? this.${f.name},')
      .join('\n');
  final toStringFields =
      effective.map((f) => '${f.name}: \$${f.name}').join(', ');

  return '''
/// Data model for $className. Generated by river_cli.
class $className {
$declarations

  const $className({
$ctorParams
  });

  factory $className.fromJson(Map<String, dynamic> json) => $className(
$fromJson
      );

  Map<String, dynamic> toJson() => {
$toJson
      };

  $className copyWith({
$copyParams
  }) =>
      $className(
$copyAssign
      );

  @override
  String toString() => '$className($toStringFields)';
}
''';
}

/// A repository. When the `network` module is installed it extends
/// `BaseRepository` and uses the shared `APIProvider`; otherwise it emits a
/// self-contained stub with TODOs so the file still compiles.
String repositoryTemplate(String name, ProjectContext ctx) {
  final className = '${Naming.pascal(name)}Repository';
  final modelName = Naming.pascal(name);
  final pkg = ctx.packageName ?? 'app';
  final endpointConst = Naming.camel(name);

  if (ctx.hasNetwork) {
    return '''
import 'package:$pkg/data/models/${Naming.snake(name)}_model.dart';
import '../provider/network/api_endpoints.dart';
import 'repository.dart';

/// Repository for $modelName resources. Add the matching paths to
/// [ApiEndPoints] (e.g. `static const String $endpointConst = '$endpointConst';`).
class $className extends BaseRepository {
  Future<List<$modelName>> fetchAll() async {
    final response = await api.get(ApiEndPoints.$endpointConst);
    final list = (response as List).cast<Map<String, dynamic>>();
    return list.map($modelName.fromJson).toList();
  }

  Future<$modelName> fetchById(String id) async {
    final response = await api.get('\${ApiEndPoints.$endpointConst}/\$id');
    return $modelName.fromJson(response as Map<String, dynamic>);
  }

  Future<$modelName> create($modelName item) async {
    final response = await api.post(
      ApiEndPoints.$endpointConst,
      body: item.toJson(),
    );
    return $modelName.fromJson(response as Map<String, dynamic>);
  }

  Future<$modelName> update(String id, $modelName item) async {
    final response = await api.put(
      '\${ApiEndPoints.$endpointConst}/\$id',
      body: item.toJson(),
    );
    return $modelName.fromJson(response as Map<String, dynamic>);
  }

  Future<void> delete(String id) =>
      api.delete('\${ApiEndPoints.$endpointConst}/\$id');
}
''';
  }

  return '''
import 'package:$pkg/data/models/${Naming.snake(name)}_model.dart';

/// Repository for $modelName resources.
///
/// The `network` module is not installed, so these methods are stubs. Run
/// `river_cli init --modules network` to wire this up to the Dio APIProvider.
class $className {
  Future<List<$modelName>> fetchAll() async {
    // TODO: fetch from your data source.
    return <$modelName>[];
  }

  Future<$modelName> fetchById(String id) {
    throw UnimplementedError('fetchById is not implemented yet.');
  }

  Future<$modelName> create($modelName item) async => item;

  Future<$modelName> update(String id, $modelName item) async => item;

  Future<void> delete(String id) async {}
}
''';
}

/// An `AsyncNotifier`-based CRUD controller that delegates to the repository.
String crudControllerTemplate(String name, ProjectContext ctx) {
  final className = '${Naming.pascal(name)}Controller';
  final modelName = Naming.pascal(name);
  final repoName = '${Naming.pascal(name)}Repository';
  final pkg = ctx.packageName ?? 'app';
  final snake = Naming.snake(name);

  return '''
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:$pkg/data/models/${snake}_model.dart';
import 'package:$pkg/data/repositories/${snake}_repository.dart';

/// Loads and mutates the list of $modelName items. All business logic lives
/// here; the view stays declarative and reads state via `ref.watch`.
class $className extends AsyncNotifier<List<$modelName>> {
  final $repoName _repository = $repoName();

  @override
  Future<List<$modelName>> build() => _repository.fetchAll();

  /// Re-fetches the list, surfacing errors through [AsyncValue].
  Future<void> refresh() async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(_repository.fetchAll);
  }

  Future<void> add($modelName item) async {
    await _repository.create(item);
    await refresh();
  }

  Future<void> update(String id, $modelName item) async {
    await _repository.update(id, item);
    await refresh();
  }

  Future<void> remove(String id) async {
    await _repository.delete(id);
    await refresh();
  }
}
''';
}

/// The Riverpod provider binding for the CRUD controller.
String crudBindingTemplate(String name) {
  final className = '${Naming.pascal(name)}Controller';
  final modelName = Naming.pascal(name);
  final provider = '${Naming.camel(name)}ControllerProvider';

  return '''
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../controllers/${Naming.snake(name)}_controller.dart';

/// Provider for [$className].
final $provider =
    AsyncNotifierProvider<$className, List<$modelName>>($className.new);
''';
}

/// A list view bound to the CRUD controller, with loading/error/empty states.
/// Uses the widget library + design tokens when those modules are installed.
String crudViewTemplate(
    String name, List<FieldSpec> fields, ProjectContext ctx) {
  final viewName = '${Naming.pascal(name)}View';
  final modelName = Naming.pascal(name);
  final title = Naming.title(name);
  final provider = '${Naming.camel(name)}ControllerProvider';
  final snake = Naming.snake(name);
  final pkg = ctx.packageName ?? 'app';

  // Pick the primary field to display per row (first non-list field, or first).
  final display = fields.isEmpty
      ? 'item.toString()'
      : 'item.${(fields.firstWhere((f) => !f.fullType.startsWith('List'), orElse: () => fields.first)).displayExpr}';

  final imports = <String>[
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "import '../bindings/${snake}_binding.dart';",
  ];

  // Convention-aware fragments.
  final String appBarTitle;
  final String emptyState;
  final String errorState;
  final String loadingState;
  final String refreshOpen;
  final String refreshClose;

  if (ctx.hasWidgets) {
    imports
      ..add("import 'package:$pkg/app/shared_widgets/my_text.dart';")
      ..add("import 'package:$pkg/app/shared_widgets/empty_state_widget.dart';")
      ..add("import 'package:$pkg/app/shared_widgets/app_error_banner.dart';")
      ..add(
          "import 'package:$pkg/app/shared_widgets/custom_loading_spinner.dart';")
      ..add(
          "import 'package:$pkg/app/shared_widgets/app_refresh_indicator.dart';");
    appBarTitle = "const MyText(title: '$title')";
    emptyState = 'const EmptyStateWidget()';
    errorState = 'AppErrorBanner(message: error.toString())';
    loadingState = 'const CustomLoadingSpinner()';
    refreshOpen =
        'AppRefreshIndicator(\n        onRefresh: () => ref.read($provider.notifier).refresh(),\n        child: ';
    refreshClose = ',\n      )';
  } else {
    appBarTitle = "const Text('$title')";
    emptyState = "const Center(child: Text('No items yet.'))";
    errorState = "Center(child: Text(error.toString()))";
    loadingState = 'const Center(child: CircularProgressIndicator())';
    refreshOpen =
        'RefreshIndicator(\n        onRefresh: () => ref.read($provider.notifier).refresh(),\n        child: ';
    refreshClose = ',\n      )';
  }

  final rowTitle =
      ctx.hasWidgets ? 'MyText(title: $display)' : 'Text($display)';

  return '''
${imports.join('\n')}

class $viewName extends ConsumerWidget {
  const $viewName({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch($provider);
    return Scaffold(
      appBar: AppBar(title: $appBarTitle),
      body: state.when(
        loading: () => $loadingState,
        error: (error, _) => $errorState,
        data: (items) {
          if (items.isEmpty) return $emptyState;
          return ${refreshOpen}ListView.separated(
          itemCount: items.length,
          separatorBuilder: (_, __) => const Divider(height: 1),
          itemBuilder: (context, index) {
            final item = items[index];
            return ListTile(
              title: $rowTitle,
            );
          },
        )$refreshClose;
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          // TODO: open a form and call ref.read($provider.notifier).add($modelName(...))
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
''';
}

/// A reusable widget placed in the shared widgets folder, following the library
/// naming style. Uses MyText/AppColors when those modules are present.
String widgetTemplate(String name, ProjectContext ctx) {
  final className = Naming.pascal(name);
  final pkg = ctx.packageName ?? 'app';

  final imports = <String>["import 'package:flutter/material.dart';"];
  final String label;
  if (ctx.hasWidgets) {
    imports.add("import 'package:$pkg/app/shared_widgets/my_text.dart';");
    label = "const MyText(title: '$className')";
  } else {
    label = "const Text('$className')";
  }

  return '''
${imports.join('\n')}

/// A reusable $className widget. Generated by river_cli.
class $className extends StatelessWidget {
  const $className({super.key});

  @override
  Widget build(BuildContext context) {
    return $label;
  }
}
''';
}

/// Renders one or more [ModelDef]s (root model plus any nested models inferred
/// from JSON) into a single Dart file.
String modelsFileTemplate(List<ModelDef> models) {
  return models.map((m) => modelTemplate(m.name, m.fields)).join('\n');
}

/// A `flutter_test` round-trip test asserting `fromJson`/`toJson` are inverse
/// for the model. Only valid for models whose fields are all primitive/list/
/// DateTime (the caller skips it when any field is a nested model).
String modelTestTemplate(
    String name, List<FieldSpec> fields, ProjectContext ctx) {
  final className = Naming.pascal(name);
  final snake = Naming.snake(name);
  final pkg = ctx.packageName ?? 'app';
  final effective =
      fields.isEmpty ? const [FieldSpec('id', 'String', false)] : fields;

  final jsonEntries = effective
      .map((f) => "      '${f.name}': ${f.sampleLiteral().json},")
      .join('\n');

  return '''
import 'package:flutter_test/flutter_test.dart';
import 'package:$pkg/data/models/${snake}_model.dart';

void main() {
  test('$className round-trips through JSON', () {
    final json = <String, dynamic>{
$jsonEntries
    };

    final model = $className.fromJson(json);

    expect(model.toJson(), json);
  });
}
''';
}
